title: secrary[dot]com
description: Does it matter?
author:
  twitter: _qaz_qaz
  
permalink: /:title

sass:
  style: :compressed
  sass_dir: _sass


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
