name: Lasha Khasaia
description: Does it matter?
url: secrary.com
author: Lasha Khasaia

permalink: /:title

twitter:
  username: _qaz_qaz

sass:
  style: :compressed
  sass_dir: _sass


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
